# Generated by Django 5.1.3 on 2024-11-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_exercises_students_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='coach_name',
            new_name='coach_id',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='classes',
            new_name='classes_id',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='student_name',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='coach_name',
            new_name='coach_id',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='students_name',
            new_name='students_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='coach_name',
            new_name='coach_id',
        ),
    ]
