# Generated by Django 5.1.3 on 2024-11-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_rename_coach_name_classes_coach_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='coach_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='exercises',
        ),
    ]
