# Generated by Django 5.1.3 on 2024-11-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_remove_student_coach_id_remove_student_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
